//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RussianCosmeticsApp.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public int ID_Clients { get; set; }
        public string NameCompany { get; set; }
        public string Addres { get; set; }
        public string INN { get; set; }
        public string Payment { get; set; }
        public string BIK { get; set; }
        public string FIO_Head { get; set; }
        public string FIO_Contact { get; set; }
        public string PhoneContact { get; set; }
        public string EmailPhysical { get; set; }
        public string PasswordPhysical { get; set; }
        public string FIOPhysical { get; set; }
        public Nullable<System.DateTime> DateBirthPhysical { get; set; }
        public string SeriaPassportPhysical { get; set; }
        public string NumberPassportPhysical { get; set; }
        public string PhonePhysicale { get; set; }

    }
}
