//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RussianCosmeticsApp.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompleteService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompleteService()
        {
            this.Personal1 = new HashSet<Personal>();
        }
    
        public int ID_CompleteService { get; set; }
        public Nullable<int> ID_Service { get; set; }
        public Nullable<int> ID_Personal { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Personal Personal { get; set; }
        public virtual Service Service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Personal> Personal1 { get; set; }
    }
}
