//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RussianCosmeticsApp.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RussianCosmeticsEntities : DbContext
    {
        private static RussianCosmeticsEntities _context;
        public RussianCosmeticsEntities()
            : base("name=RussianCosmeticsEntities")
        {
        }

        public static RussianCosmeticsEntities GetContext()
        {
            if (_context == null) _context = new RussianCosmeticsEntities();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<CompleteService> CompleteService { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OtherPersonal> OtherPersonal { get; set; }
        public virtual DbSet<Personal> Personal { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
