//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RussianCosmeticsApp.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID_Order { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<int> ID_Service { get; set; }
        public string StatusOrder { get; set; }
        public string StatusService { get; set; }
        public string TimeComplete { get; set; }
        public string CostOrder { get; set; }
        public Nullable<int> ID_Client { get; set; }
    
        public virtual Service Service { get; set; }
    }
}
